## Mod 5 Lecture 4 Code-Along:  Funnels in Python

### Goals
* Create conversion rates at each funnel step 


### Data
We are using just sample "toy" data to just illustrate the calculations (aka make it easier to digest)

In [1]:
import pandas as pd
import numpy as np

### Task 1:  Create Steps & User Counts
Note if your data has a column that is called "marketing channel" or "user entry point" you can filter for each channel/entry point and get counts etc :)

In [2]:
# Step labels and user counts
data = {
    'step_name': [
        'Visited Homepage', 'Viewed Item',
        'Added to Cart', 'Reached Checkout', 'Completed Purchase'
    ],
    'user_count': [10000, 4000, 1000, 500, 400]
}

df = pd.DataFrame(data)
df

            step_name  user_count
0    Visited Homepage       10000
1         Viewed Item        4000
2       Added to Cart        1000
3    Reached Checkout         500
4  Completed Purchase         400

### Task 2:  Calculate and add conversion rates to the dataframe

Students:  What do you think shift(1) does here?

In [14]:
# Step-to-step conversion
df['step_conversion'] = df['user_count'] / df['user_count'].shift(1)

# Overall conversion from the first step
df['overall_conversion'] = df['user_count'] / df['user_count'].iloc[0]

# Format as percentages
df['step_conversion'] = (df['step_conversion'] * 100).round(2)
df['overall_conversion'] = (df['overall_conversion'] * 100).round(2)
df

            step_name  user_count  step_conversion  overall_conversion
0    Visited Homepage       10000              NaN               100.0
1         Viewed Item        4000             40.0                40.0
2       Added to Cart        1000             25.0                10.0
3    Reached Checkout         500             50.0                 5.0
4  Completed Purchase         400             80.0                 4.0

### Task 3:  Interpret the Funnel

Students:  We print out the results again and add it as a nice markdown table below the output for ease of interpretation.  What are the main insights here?

In [16]:
print(df[['step_name', 'user_count', 'step_conversion', 'overall_conversion']])

            step_name  user_count  step_conversion  overall_conversion
0    Visited Homepage       10000              NaN               100.0
1         Viewed Item        4000             40.0                40.0
2       Added to Cart        1000             25.0                10.0
3    Reached Checkout         500             50.0                 5.0
4  Completed Purchase         400             80.0                 4.0

| Step          | Users | Step Conv. | Overall Conv. |
| ------------- | ----- | ---------- | ------------- |
| Viewed Item   | 4,000 | 40%        | 40%           |
| Added to Cart | 1,000 | 25%        | 10%           |
| Checkout      | 500   | 50%        | 5%            |
| Purchase      | 400   | 80%        | 4%            |